export enum InviteeType {
  PERSON = 'PERSON',
  CHOIR = 'CHOIR',
  MINISTRY = 'MINISTRY',
  BAND = 'BAND',
  WORSHIP_TEAM = 'WORSHIP_TEAM',
  DANCE_GROUP = 'DANCE_GROUP',
  ORGANIZATION = 'ORGANIZATION',
  CHURCH = 'CHURCH',
  DELEGATION = 'DELEGATION',
  MEDIA_HOUSE = 'MEDIA_HOUSE',
  OTHER_GROUP = 'OTHER_GROUP',
}
